apiVersion: batch/v1
kind: CronJob
metadata:
  name: dawatch
  namespace: dawatch
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dawatch
              imagePullPolicy: IfNotPresent
