apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-cluster-backend
    kind: ClusterSecretStore
  target:
    name: dawatch-secrets
    creationPolicy: Owner
  data:
    - secretKey: DEVIANTART_CLIENT_ID
      remoteRef:
        key: deviantart/config
        property: DEVIANTART_CLIENT_ID
    - secretKey: DEVIANTART_CLIENT_SECRET
      remoteRef:
        key: deviantart/config
        property: DEVIANTART_CLIENT_SECRET
    - secretKey: DAWATCH_NTFY_TOPIC
      remoteRef:
        key: deviantart/config
        property: DAWATCH_NTFY_TOPIC
    - secretKey: DAWATCH_REFRESH_TOKEN
      remoteRef:
        key: deviantart/config
        property: DAWATCH_REFRESH_TOKEN
