apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dawatch

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - cronjob.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: dawatch
      app.kubernetes.io/part-of: dawatch
